apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ackdemo.fullname" . }}-mongo-express
  labels:
  {{- include "ackdemo.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.mongoExpress.replicas }}
  selector:
    matchLabels:
      app: mongo-express
    {{- include "ackdemo.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: mongo-express
      {{- include "ackdemo.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: ME_CONFIG_MONGODB_ADMINUSERNAME
          valueFrom:
            secretKeyRef:
              key: mongo-root-username
              name: {{ include "ackdemo.fullname" . }}-mongodb-secret
        - name: ME_CONFIG_MONGODB_ADMINPASSWORD
          valueFrom:
            secretKeyRef:
              key: mongo-root-password
              name: {{ include "ackdemo.fullname" . }}-mongodb-secret
        - name: ME_CONFIG_MONGODB_SERVER
          valueFrom:
            configMapKeyRef:
              key: database_url
              name: {{ include "ackdemo.fullname" . }}-mongodb-configmap
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: {{ .Values.mongoExpress.mongoExpress.image.repository }}:{{ .Values.mongoExpress.mongoExpress.image.tag
          | default .Chart.AppVersion }}
        name: mongo-express
        ports:
        - containerPort: 8081
        resources: {{- toYaml .Values.mongoExpress.mongoExpress.resources | nindent 10
          }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ackdemo.fullname" . }}-mongodb-deployment
  labels:
  {{- include "ackdemo.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.mongodbDeployment.replicas }}
  selector:
    matchLabels:
      app: mongodb
    {{- include "ackdemo.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: mongodb
      {{- include "ackdemo.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              key: mongo-root-username
              name: {{ include "ackdemo.fullname" . }}-mongodb-secret
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: mongo-root-password
              name: {{ include "ackdemo.fullname" . }}-mongodb-secret
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: {{ .Values.mongodbDeployment.mongodb.image.repository }}:{{ .Values.mongodbDeployment.mongodb.image.tag
          | default .Chart.AppVersion }}
        name: mongodb
        ports:
        - containerPort: 27017
        resources: {{- toYaml .Values.mongodbDeployment.mongodb.resources | nindent 10
          }}