apiVersion: v1
kind: Service
metadata:
  name: {{ include "ackdemo.fullname" . }}-mongo-express-service
  labels:
  {{- include "ackdemo.labels" . | nindent 4 }}
spec:
  type: {{ .Values.mongoExpressService.type }}
  selector:
    app: mongo-express
  {{- include "ackdemo.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.mongoExpressService.ports | toYaml | nindent 2 -}}