apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ackdemo.fullname" . }}-mongodb-configmap
  labels:
  {{- include "ackdemo.labels" . | nindent 4 }}
data:
  database_url: {{ include "ackdemo.fullname" . }}-{{ .Values.mongodbConfigmap.databaseUrl }}