apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ackdemo.fullname" . }}-mongodb-secret
  labels:
  {{- include "ackdemo.labels" . | nindent 4 }}
data:
  mongo-root-password: {{ required "mongodbSecret.mongoRootPassword is required"
    .Values.mongodbSecret.mongoRootPassword | b64enc | quote }}
  mongo-root-username: {{ required "mongodbSecret.mongoRootUsername is required"
    .Values.mongodbSecret.mongoRootUsername | b64enc | quote }}
type: Opaque